config/routes.rb
Yourownstagram::Application.routes.draw do
  root "images#index"
  
  devise_for :users
  
  get '/users/:id', to: 'users#show'

  scope :api do
    resources :images do
      # comment routes
      get '/api/images/:id/comments', to: 'comments#index'
      get '/api/images/:id/comments/:id', to: 'comments#show'
      post '/api/images/:id/comments', to: 'comments#new'

      # like routes
      post '/api/images/:id/likes', to: 'likes#new'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  # Carrierwave uploader
  mount_uploader :attachment, ImageUploader
  belongs_to :user
  has_many :comments
  has_many :likes
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/index.html.erb
<p>This is the index page for my images</p>


<p>Loading...</p>

app/views/images/new.html.erb
<p>This is where I generate a new image</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>

  </body>
</html>

app/views/users/show.html.erb
<p>This is the show page for a user</p>

<%= @user.email %>

<%= link_to("Upload a new picture", new_image_path) %>